version: '3'
services:
    comet:
        image: comet
        build:
            context: ./gateway
            dockerfile: Dockerfile
        volumes:
            - ./comet/.env:/data/.env:ro
            # - /data/docker-dev/runtime/nginx/conf.d/certs:/data/certs:ro
        ports:
            - 8900:8900
            - 8901:8901
        command: -c /data/.env

    # 说明:
    # port: 6379
    # conf: /usr/local/etc/redis/redis.conf
    # redis:
    #     image: redis:3.2
    #     container_name: container-redis
    #     restart: always
    #     ports:
    #         - 6379:6379
