version: '3'
services:
    comet-monitor-01:
        image: comet
        build:
            context: ./comet
            dockerfile: Dockerfile
        volumes:
            - ./comet/comet.ini:/data/comet.ini:ro
        command: -c /data/comet.ini -m
        depends_on:
            - etcd-01

    comet-01:
        image: comet
        build:
            context: ./comet
            dockerfile: Dockerfile
        volumes:
            - ./comet/comet.ini:/data/comet.ini:ro
        ports:
            - 8900:8900
            - 8901:8901
        command: -c /data/comet.ini
        depends_on:
            - etcd-01

    etcd-01:
        image: quay.io/coreos/etcd:v3.3.1
        ports:
            - 2379:2379
            - 2380:2380
        environment:
            - ETCDCTL_API=3
        volumes:
            - ./runtime/etcd-01:/etcd-data
        command:  >-
            /usr/local/bin/etcd
            --data-dir=/etcd-data
            -name etcd-01
            -advertise-client-urls http://${HOST_IP}:2379
            -listen-client-urls http://0.0.0.0:2379
            -initial-advertise-peer-urls http://${HOST_IP}:2380
            -listen-peer-urls http://0.0.0.0:2380
            -initial-cluster etcd-01=http://${HOST_IP}:2380

    # 说明:
    # port: 6379
    # conf: /usr/local/etc/redis/redis.conf
    redis:
        image: redis:3.2
        container_name: container-redis
        restart: always
        ports:
            - 6379:6379
